using IronPython.Hosting;
using Microsoft.Scripting.Hosting;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Advance_Text_Detector
{
    public partial class Form1 : Form
    {
        string result;

        public Form1()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if(textBox1.Text==""||textBox1.Text=="Can't be empty!")
            {
                textBox1.Text = "Can't be empty!";
            }
            else
            {
                File.WriteAllText("umeaning.txt", String.Empty);
                backgroundWorker1.RunWorkerAsync();
            } 
        }

        private void button2_Click(object sender, EventArgs e)
        {
            OpenFileDialog openFileDialog = new OpenFileDialog();
            openFileDialog.Filter = "Image Files|*.jpg;*.jpeg;*.png;...";
            openFileDialog.ShowDialog();
            textBox1.Text = openFileDialog.FileName;
            File.WriteAllText("D:/TxtDetect/path.txt", String.Empty);
            FileStream f = new FileStream("D:/TxtDetect/path.txt", FileMode.OpenOrCreate, FileAccess.Write);
            StreamWriter w = new StreamWriter(f);
            w.Write(openFileDialog.FileName);
            w.Close();
        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {
            
            RichTextBox.CheckForIllegalCrossThreadCalls = false;

            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "C:/Users/siddh/AppData/Local/Programs/Python/Python39/python.exe";
            start.Arguments = string.Format("{0}", "D:/TxtDetect/try.py");
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    result = reader.ReadToEnd();
                    Console.Write(result);
                }
            }
        }

        private void backgroundWorker1_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
        {

            FileStream fs1 = new FileStream("D:/TxtDetect/meaning.txt", FileMode.Append, FileAccess.Write) ;
            StreamWriter writer = new StreamWriter(fs1);
            writer.Write(result);
            writer.Close();
            
            string text = File.ReadAllText("D:/TxtDetect/meaning.txt");
            text = text.Replace("Error: The Following Error occured: list index out of range", " ");
            File.WriteAllText("D:/TxtDetect/meaning.txt", text);

            string entire = File.ReadAllText(@"D:/TxtDetect/meaning.txt");
            richTextBox1.Text = entire;

        }

        private void button3_Click(object sender, EventArgs e)
        {
            Form2 f2 = new Form2();
            this.Hide();
            f2.Show();
        }
    }
}

//C:/Users/siddh/AppData/Local/Programs/Python/Python39/python.exe
//D:/TxtDetect/detectit.py


/*File.WriteAllText("D:/AVScriptsFinal/text/MD5link.txt", String.Empty);
FileStream fs1 = new FileStream("D:/AVScriptsFinal/text/MD5link.txt", FileMode.OpenOrCreate, FileAccess.Write);
StreamWriter writer = new StreamWriter(fs1);
writer.Write(textBox1.Text);
writer.Close();*/

/*string content = File.ReadAllText(@"D:\AVScriptsFinal\VirusDB\MD5CalculatedDB\MD5CalculatedDB.txt");
richTextBox2.Text = content;*/