using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Advance_Text_Detector
{
    public partial class Form2 : Form
    {
        string result;

        public Form2()
        {
            InitializeComponent();
        }

        private void button1_Click(object sender, EventArgs e)
        {
            if (textBox1.Text == "" || textBox1.Text == "Can't be empty!")
            {
                textBox1.Text = "Can't be empty!";
            }
            else
            {
                File.WriteAllText("D:/TxtDetect/mean.txt", String.Empty);
                File.WriteAllText("D:/TxtDetect/data.txt", textBox1.Text);
                backgroundWorker1.RunWorkerAsync();
            }
        }

        private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = "C:/Users/siddh/AppData/Local/Programs/Python/Python39/python.exe";
            start.Arguments = string.Format("{0}", "D:/TxtDetect/meaning.py");
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    result = reader.ReadToEnd();
                    Console.Write(result);
                }
            }
        }

        private void backgroundWorker1_RunWorkerCompleted(object sender, RunWorkerCompletedEventArgs e)
        {
            FileStream fs1 = new FileStream("D:/TxtDetect/mean.txt", FileMode.Append, FileAccess.Write);
            StreamWriter writer = new StreamWriter(fs1);
            writer.Write(result);
            writer.Close();

            string text = File.ReadAllText("D:/TxtDetect/mean.txt");
            text = text.Replace("Error: The Following Error occured: list index out of range", " ");
            File.WriteAllText("D:/TxtDetect/mean.txt", text);

            string entire = File.ReadAllText(@"D:/TxtDetect/mean.txt");
            richTextBox1.Text = entire;
        }

        private void button3_Click(object sender, EventArgs e)
        {
            Form1 f1 = new Form1();
            this.Hide();
            f1.Show();
        }
    }
}
